name: Generate and Store Keys

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate RSA Key
        id: generate-key
        run: |
          openssl genpkey -algorithm RSA -out private.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -in private.pem -pubout -out public.pem
          echo "PRIVATE_KEY=$(cat private.pem)" >> secrets.env
          echo "PUBLIC_KEY=$(cat public.pem)" >> secrets.env
          echo "PRIVATE_KEY_PATH=$GITHUB_WORKSPACE/private.pem" >> secrets.env
          echo "PUBLIC_KEY_PATH=$GITHUB_WORKSPACE/public.pem" >> secrets.env
          cat secrets.env >> $GITHUB_ENV

      - name: Output Secrets in the workflow
        run: |
          echo "PRIVATE_KEY: ${{ env.PRIVATE_KEY }}"
          echo "PUBLIC_KEY: ${{ env.PUBLIC_KEY }}"
          echo "PRIVATE_KEY_PATH: ${{ env.PRIVATE_KEY_PATH }}"
          echo "PUBLIC_KEY_PATH: ${{ env.PUBLIC_KEY_PATH }}"

      #For extra security measures
      - name: Delete Private Key
        run: rm private.pem
